# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "trufina"
  s.version = "0.3.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Kali Donovan"]
  s.date = "2012-12-05"
  s.description = "Provides a DSL to easily interact with the XML API offered by Trufina.com, an identity verification company."
  s.email = "kali.donovan@gmail.com"
  s.extra_rdoc_files = [
    "README.rdoc",
    "TODO"
  ]
  s.files = [
    "CHANGELOG",
    "MIT-LICENSE",
    "README.rdoc",
    "Rakefile",
    "TODO",
    "VERSION",
    "init.rb",
    "lib/config.rb",
    "lib/elements.rb",
    "lib/exceptions.rb",
    "lib/requests.rb",
    "lib/responses.rb",
    "lib/trufina.rb",
    "rails/init.rb",
    "tasks/trufina_tasks.rake",
    "test/fixtures/requests/access_request.xml",
    "test/fixtures/requests/info_request.xml",
    "test/fixtures/requests/login_info_request.xml",
    "test/fixtures/requests/login_request.xml",
    "test/fixtures/requests/login_request_simple.xml",
    "test/fixtures/responses/access_notification.xml",
    "test/fixtures/responses/access_response.xml",
    "test/fixtures/responses/info_response.xml",
    "test/fixtures/responses/login_info_response.xml",
    "test/fixtures/responses/login_response.xml",
    "test/fixtures/schema.xsd",
    "test/test_helper.rb",
    "test/trufina_test.rb",
    "trufina.gemspec",
    "trufina.yml.template"
  ]
  s.homepage = "http://github.com/kdonovan/trufina"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.15"
  s.summary = "DSL to easily interact with Trufina's verification API"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<kdonovan-happymapper>, [">= 0"])
    else
      s.add_dependency(%q<kdonovan-happymapper>, [">= 0"])
    end
  else
    s.add_dependency(%q<kdonovan-happymapper>, [">= 0"])
  end
end

